### ISSUE TITLE
Cannot do do newlines

### ISSUE THREAD

**Issue by David-Hinschberger** [Luke-Dramko/regen#2]
There doesn't seem to be a way to specify new lines in the pattern to create.

**Comment by Luke-Dramko** [comment]
Currently, there is no way to add newlines - the reason for this is that it may be confusing if used in conjunction with the `-l` option. An escaped character simply functions as that character without any special meanings attached - `\+`, for example, is rendered as `+`, whereas using `+` without an escape results in a parse error.

That being said, having `\n` be functional in a regular expression is strictly more powerful than the `-l` option:
   `regen 'regex' -l x`
is equivalent to
   `regen '(regex\n){x}`
where `x` is some positive integer, but the second allows the interleaving of newlines into a given expression.

**Comment by Luke-Dramko** [comment]
Support for newlines has been added with #3.
